background {
    monitor =
    path = /home/koji/.local/share/wallpapers/Kath.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(73BA25)
    inner_color = rgb(1B1D21)
    font_color = rgb(D4D4D4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%a %d %B  %H:%M'
    color = rgb(73BA25)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
