################
### MONITORS ###
################

monitor=eDP-1,preferred,auto,auto
monitor=,preferred,auto,auto


###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = ~/.config/hypr/scripts/wofi-launcher.sh --show drun


#################
### AUTOSTART ###
#################

exec-once = /usr/libexec/polkit-kde-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd --all
exec-once = xhost +SI:localuser:root
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = LC_TIME=it_IT.utf8 waybar
exec-once = ~/.config/hypr/scripts/monitor-switch.sh
exec-once = hyprpaper
exec-once = mako
exec-once = blueman-applet
exec-once = nm-applet --indicator


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,kde


#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border =
